spring.application.name=animal-service
server.port=8085

spring.datasource.url=jdbc:h2:mem:db-animais
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Força o Hibernate a criar as tabelas
spring.jpa.hibernate.ddl-auto=none
# Mostra o comando de criação no console
spring.jpa.show-sql=true
# Ajuda o Spring a encontrar as entidades
spring.entityscan.base-packages=br.com.ebac.animal_service.entity

# spring.datasource.url=jdbc:h2:file:/ebac/animais
